In [16]:
import pandas as pd
import geopy.distance
from sklearn.neighbors import KNeighborsClassifier
from geopy import Nominatim
import requests
import os

In [17]:
tf=pd.read_csv('시장및마트현황.csv',encoding='EUC-KR')
tf

,시군명,시설구분명,시장명,전화번호,소재지우편번호,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
0,광명시,로컬푸드직매장,광명농협 로컬푸드 직매장,02-2169-8092,14316,경기도 광명시 금하로 450,경기도 광명시 소하동 1340-3번지,37.448321,126.882294
1,광명시,전통시장,NaN,02-2614-0006,14220,경기도 광명시 광이로13번길 17-5,경기도 광명시 광명동 158-44,37.479948,126.856165
2,광명시,전통시장,NaN,02-2614-5292,14291,경기도 광명시 광명로 831번지 4의1,경기도 광명시 광명동 342-12,37.473654,126.851400
3,고양시,로컬푸드직매장,신도농협 로컬푸드직매장,02-381-0100,10584,경기도 고양시 덕양구 백운길 22,경기도 고양시 덕양구 지축동 300번지,37.652333,126.934864
4,부천시,전통시장,NaN,02-754-7389,14495,경기도 부천시 평천로 719,경기도 부천시 삼정동 314-13,37.515338,126.770583
...,...,...,...,...,...,...,...,...,...
1062,이천시,대규모점포,(주)이마트에브리데이 이천갈산점,NaN,17359,경기도 이천시 안흥로 70 (갈산동),경기도 이천시 갈산동 602번지,37.284062,127.455338
1063,김포시,대규모점포,GS THE FRESH 김포구래점,NaN,10063,"경기도 김포시 김포한강4로420번길 88, 슈퍼스타타워 101호, 102호, 113...",경기도 김포시 구래동 6874-23,37.650655,126.633167
1064,용인시,대규모점포,링크맘,NaN,16995,경기도 용인시 기흥구 동백죽전대로175번길 6 (중동),경기도 용인시 기흥구 중동 31-5,37.257641,127.160446
1065,의정부시,대규모점포,홈플러스의정부점,NaN,11757,경기도 의정부시 청사로 38 (금오동),경기도 의정부시 금오동 475번지 1호,37.752170,127.071018
1066,안양시,대규모점포,롯데슈퍼 평촌엘프가맹점,NaN,13917,"경기도 안양시 동안구 매곡로 23, 1단지상가 122호 (비산동, 평촌엘프라우드)",경기도 안양시 동안구 비산동 281-1 1단지상가 122호,37.406571,126.944410

In [18]:
KAKAO_API_KEY = os.getenv('KAKAO_API_KEY')

def kakao_geocode(address: str):
    url = f"https://dapi.kakao.com/v2/local/search/address.json?query={address}"
    headers = {"Authorization": f"KakaoAK {KAKAO_API_KEY}"}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        result = response.json()
        if result['documents']:
            location = result['documents'][0]['address']
            return float(location['y']), float(location['x'])
    return None, None

In [21]:
kakao_geocode('경기도 남양주시 와부읍 덕소리 483 외1호')

(37.5876516894019, 127.213064844527)

In [24]:
tf=tf[tf['시군명']=="남양주시"]
tf

,시군명,시설구분명,시장명,전화번호,소재지우편번호,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
67,남양주시,로컬푸드직매장,진접농협 로컬푸드직매장,031-567-8605,12067,경기도 남양주시 진접읍 해밀예당1로 28,경기도 남양주시 진접읍 연평리 56번지,37.711262,127.186172
70,남양주시,로컬푸드직매장,와부농협 로컬푸드직매장,031-577-4008,12203,경기도 남양주시 와부읍 수레로 150,경기도 남양주시 와부읍 월문리 1249-1번지,37.594130,127.224952
219,남양주시,전통시장,NaN,NaN,12013,경기도 남양주시 진접읍 장현로 77의100,경기도 남양주시 장현리 380-15,37.717616,127.180891
344,남양주시,대규모점포,(주)이마트 다산점,NaN,NaN,"경기도 남양주시 도농로 24 (다산동, 부영애시앙)",경기도 남양주시 다산동 4001번지 29호,NaN,NaN
348,남양주시,대규모점포,LG마트 덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33 (덕소리),경기도 남양주시 와부읍 덕소리 501-3호,37.584595,127.214505
425,남양주시,대규모점포,(주)이마트 남양주점,NaN,472-120,경기도 남양주시 늘을2로 27 (호평동),경기도 남양주시 호평동 637번지,37.655012,127.243082
452,남양주시,대규모점포,롯데쇼핑(주)롯데마트덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33,경기도 남양주시 와부읍 덕소리 501-3호,37.584694,127.214023
521,남양주시,대규모점포,홈플러스(주)남양주진접점,NaN,472-865,경기도 남양주시 진접읍 금강로 1447,경기도 남양주시 진접읍 장현리 216번지 1호,37.721750,127.188601
718,남양주시,대규모점포,이마트 별내점,NaN,12113,"경기도 남양주시 순화궁로 167, 이마트 (별내동)",경기도 남양주시 별내동 989번지 이마트,37.642846,127.125942
808,남양주시,대규모점포,선플렉스미트,NaN,NaN,NaN,경기도 남양주시 와부읍 덕소리 483 외1호,NaN,NaN
820,남양주시,대규모점포,롯데쇼핑(주)롯데마트 마석점,NaN,472845,경기도 남양주시 화도읍 경춘로 1992,경기도 남양주시 화도읍 마석우리 255번지 24호,37.650144,127.309302
842,남양주시,대규모점포,주식회사 이마트 진접점,NaN,12073,"경기도 남양주시 진접읍 금강로유연들1길 154, 진접이마트",경기도 남양주시 진접읍 연평리 101번지 14호 진접이마트,37.708799,127.181996
996,남양주시,대규모점포,한성몰 남양주점,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368-2,37.656549,127.281589
997,남양주시,대규모점포,코리아마트,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368번지 2호,37.656549,127.281589
1052,남양주시,대규모점포,현대프리미엄아울렛 SPACE1,NaN,12248,"경기도 남양주시 다산순환로 50, 다산진건 자족시설용지 1BL 판매시설 (다산동)",경기도 남양주시 다산동 6141번지 다산진건 자족시설용지 1BL 판매시설,37.616103,127.152443
1054,남양주시,대규모점포,다산역 데시앙 상업시설,NaN,NaN,NaN,경기도 남양주시 다산동 6056,37.625368,127.153281

In [35]:
tf['WGS84위도']=tf['소재지지번주소'].apply(lambda x : kakao_geocode(x)[0])
tf['WGS84경도']=tf['소재지지번주소'].apply(lambda x : kakao_geocode(x)[1])
tf

C:\Temp\ipykernel_7276\4262337233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['WGS84위도']=tf['소재지지번주소'].apply(lambda x : kakao_geocode(x)[0])
C:\Temp\ipykernel_7276\4262337233.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['WGS84경도']=tf['소재지지번주소'].apply(lambda x : kakao_geocode(x)[1])

,시군명,시설구분명,시장명,전화번호,소재지우편번호,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
67,남양주시,로컬푸드직매장,진접농협 로컬푸드직매장,031-567-8605,12067,경기도 남양주시 진접읍 해밀예당1로 28,경기도 남양주시 진접읍 연평리 56번지,37.711044,127.186060
70,남양주시,로컬푸드직매장,와부농협 로컬푸드직매장,031-577-4008,12203,경기도 남양주시 와부읍 수레로 150,경기도 남양주시 와부읍 월문리 1249-1번지,37.594166,127.224936
219,남양주시,전통시장,NaN,NaN,12013,경기도 남양주시 진접읍 장현로 77의100,경기도 남양주시 장현리 380-15,37.718363,127.182847
344,남양주시,대규모점포,(주)이마트 다산점,NaN,NaN,"경기도 남양주시 도농로 24 (다산동, 부영애시앙)",경기도 남양주시 다산동 4001번지 29호,NaN,NaN
348,남양주시,대규모점포,LG마트 덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33 (덕소리),경기도 남양주시 와부읍 덕소리 501-3호,37.585836,127.212652
425,남양주시,대규모점포,(주)이마트 남양주점,NaN,472-120,경기도 남양주시 늘을2로 27 (호평동),경기도 남양주시 호평동 637번지,37.655036,127.243061
452,남양주시,대규모점포,롯데쇼핑(주)롯데마트덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33,경기도 남양주시 와부읍 덕소리 501-3호,37.585836,127.212652
521,남양주시,대규모점포,홈플러스(주)남양주진접점,NaN,472-865,경기도 남양주시 진접읍 금강로 1447,경기도 남양주시 진접읍 장현리 216번지 1호,NaN,NaN
718,남양주시,대규모점포,이마트 별내점,NaN,12113,"경기도 남양주시 순화궁로 167, 이마트 (별내동)",경기도 남양주시 별내동 989번지 이마트,37.643138,127.126013
808,남양주시,대규모점포,선플렉스미트,NaN,NaN,NaN,경기도 남양주시 와부읍 덕소리 483 외1호,37.587652,127.213065
820,남양주시,대규모점포,롯데쇼핑(주)롯데마트 마석점,NaN,472845,경기도 남양주시 화도읍 경춘로 1992,경기도 남양주시 화도읍 마석우리 255번지 24호,37.650822,127.309282
842,남양주시,대규모점포,주식회사 이마트 진접점,NaN,12073,"경기도 남양주시 진접읍 금강로유연들1길 154, 진접이마트",경기도 남양주시 진접읍 연평리 101번지 14호 진접이마트,NaN,NaN
996,남양주시,대규모점포,한성몰 남양주점,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368-2,37.656565,127.281709
997,남양주시,대규모점포,코리아마트,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368번지 2호,NaN,NaN
1052,남양주시,대규모점포,현대프리미엄아울렛 SPACE1,NaN,12248,"경기도 남양주시 다산순환로 50, 다산진건 자족시설용지 1BL 판매시설 (다산동)",경기도 남양주시 다산동 6141번지 다산진건 자족시설용지 1BL 판매시설,37.615877,127.152730
1054,남양주시,대규모점포,다산역 데시앙 상업시설,NaN,NaN,NaN,경기도 남양주시 다산동 6056,37.625571,127.153284

In [36]:
tf['WGS84위도']=tf['소재지도로명주소'].apply(lambda x : kakao_geocode(x)[0] if x!=None else tf[tf['소재지도로명주소']==x]['WGS84위도'].values[0])
tf['WGS84경도']=tf['소재지도로명주소'].apply(lambda x : kakao_geocode(x)[1] if x!=None else tf[tf['소재지도로명주소']==x]['WGS84경도'].values[0])
tf

C:\Temp\ipykernel_7276\3600403731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['WGS84위도']=tf['소재지도로명주소'].apply(lambda x : kakao_geocode(x)[0] if x!=None else tf[tf['소재지도로명주소']==x]['WGS84위도'].values[0])
C:\Temp\ipykernel_7276\3600403731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['WGS84경도']=tf['소재지도로명주소'].apply(lambda x : kakao_geocode(x)[1] if x!=None else tf[tf['소재지도로명주소']==x]['WGS84경도'].values[0])

,시군명,시설구분명,시장명,전화번호,소재지우편번호,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
67,남양주시,로컬푸드직매장,진접농협 로컬푸드직매장,031-567-8605,12067,경기도 남양주시 진접읍 해밀예당1로 28,경기도 남양주시 진접읍 연평리 56번지,37.711246,127.186172
70,남양주시,로컬푸드직매장,와부농협 로컬푸드직매장,031-577-4008,12203,경기도 남양주시 와부읍 수레로 150,경기도 남양주시 와부읍 월문리 1249-1번지,37.594126,127.224948
219,남양주시,전통시장,NaN,NaN,12013,경기도 남양주시 진접읍 장현로 77의100,경기도 남양주시 장현리 380-15,37.717616,127.180891
344,남양주시,대규모점포,(주)이마트 다산점,NaN,NaN,"경기도 남양주시 도농로 24 (다산동, 부영애시앙)",경기도 남양주시 다산동 4001번지 29호,37.608204,127.157754
348,남양주시,대규모점포,LG마트 덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33 (덕소리),경기도 남양주시 와부읍 덕소리 501-3호,37.584697,127.214019
425,남양주시,대규모점포,(주)이마트 남양주점,NaN,472-120,경기도 남양주시 늘을2로 27 (호평동),경기도 남양주시 호평동 637번지,37.655047,127.243053
452,남양주시,대규모점포,롯데쇼핑(주)롯데마트덕소점,NaN,12211,경기도 남양주시 와부읍 월문천로 33,경기도 남양주시 와부읍 덕소리 501-3호,37.584697,127.214019
521,남양주시,대규모점포,홈플러스(주)남양주진접점,NaN,472-865,경기도 남양주시 진접읍 금강로 1447,경기도 남양주시 진접읍 장현리 216번지 1호,37.721747,127.188607
718,남양주시,대규모점포,이마트 별내점,NaN,12113,"경기도 남양주시 순화궁로 167, 이마트 (별내동)",경기도 남양주시 별내동 989번지 이마트,37.642810,127.125968
808,남양주시,대규모점포,선플렉스미트,NaN,NaN,NaN,경기도 남양주시 와부읍 덕소리 483 외1호,NaN,NaN
820,남양주시,대규모점포,롯데쇼핑(주)롯데마트 마석점,NaN,472845,경기도 남양주시 화도읍 경춘로 1992,경기도 남양주시 화도읍 마석우리 255번지 24호,37.650139,127.309296
842,남양주시,대규모점포,주식회사 이마트 진접점,NaN,12073,"경기도 남양주시 진접읍 금강로유연들1길 154, 진접이마트",경기도 남양주시 진접읍 연평리 101번지 14호 진접이마트,37.708831,127.182031
996,남양주시,대규모점포,한성몰 남양주점,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368-2,37.656536,127.281640
997,남양주시,대규모점포,코리아마트,NaN,12171,경기도 남양주시 화도읍 경춘로 1725,경기도 남양주시 화도읍 묵현리 368번지 2호,37.656536,127.281640
1052,남양주시,대규모점포,현대프리미엄아울렛 SPACE1,NaN,12248,"경기도 남양주시 다산순환로 50, 다산진건 자족시설용지 1BL 판매시설 (다산동)",경기도 남양주시 다산동 6141번지 다산진건 자족시설용지 1BL 판매시설,37.616258,127.152429
1054,남양주시,대규모점포,다산역 데시앙 상업시설,NaN,NaN,NaN,경기도 남양주시 다산동 6056,NaN,NaN

In [37]:
tf=tf[['시장명','WGS84위도','WGS84경도']]
tf

                   시장명    WGS84위도     WGS84경도
67        진접농협 로컬푸드직매장  37.711246  127.186172
70        와부농협 로컬푸드직매장  37.594126  127.224948
219                NaN  37.717616  127.180891
344         (주)이마트 다산점  37.608204  127.157754
348           LG마트 덕소점  37.584697  127.214019
425        (주)이마트 남양주점  37.655047  127.243053
452     롯데쇼핑(주)롯데마트덕소점  37.584697  127.214019
521      홈플러스(주)남양주진접점  37.721747  127.188607
718            이마트 별내점  37.642810  127.125968
808             선플렉스미트        NaN         NaN
820    롯데쇼핑(주)롯데마트 마석점  37.650139  127.309296
842       주식회사 이마트 진접점  37.708831  127.182031
996           한성몰 남양주점  37.656536  127.281640
997              코리아마트  37.656536  127.281640
1052  현대프리미엄아울렛 SPACE1  37.616258  127.152429
1054      다산역 데시앙 상업시설        NaN         NaN

In [38]:
tf['시장명'].fillna('장현 전통시장',inplace=True)
tf

C:\Temp\ipykernel_7276\2935732414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['시장명'].fillna('장현 전통시장',inplace=True)

                   시장명    WGS84위도     WGS84경도
67        진접농협 로컬푸드직매장  37.711246  127.186172
70        와부농협 로컬푸드직매장  37.594126  127.224948
219            장현 전통시장  37.717616  127.180891
344         (주)이마트 다산점  37.608204  127.157754
348           LG마트 덕소점  37.584697  127.214019
425        (주)이마트 남양주점  37.655047  127.243053
452     롯데쇼핑(주)롯데마트덕소점  37.584697  127.214019
521      홈플러스(주)남양주진접점  37.721747  127.188607
718            이마트 별내점  37.642810  127.125968
808             선플렉스미트        NaN         NaN
820    롯데쇼핑(주)롯데마트 마석점  37.650139  127.309296
842       주식회사 이마트 진접점  37.708831  127.182031
996           한성몰 남양주점  37.656536  127.281640
997              코리아마트  37.656536  127.281640
1052  현대프리미엄아울렛 SPACE1  37.616258  127.152429
1054      다산역 데시앙 상업시설        NaN         NaN

In [40]:
tf.dropna(inplace=True)
tf

C:\Temp\ipykernel_7276\3202356584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf.dropna(inplace=True)

                   시장명    WGS84위도     WGS84경도
67        진접농협 로컬푸드직매장  37.711246  127.186172
70        와부농협 로컬푸드직매장  37.594126  127.224948
219            장현 전통시장  37.717616  127.180891
344         (주)이마트 다산점  37.608204  127.157754
348           LG마트 덕소점  37.584697  127.214019
425        (주)이마트 남양주점  37.655047  127.243053
452     롯데쇼핑(주)롯데마트덕소점  37.584697  127.214019
521      홈플러스(주)남양주진접점  37.721747  127.188607
718            이마트 별내점  37.642810  127.125968
820    롯데쇼핑(주)롯데마트 마석점  37.650139  127.309296
842       주식회사 이마트 진접점  37.708831  127.182031
996           한성몰 남양주점  37.656536  127.281640
997              코리아마트  37.656536  127.281640
1052  현대프리미엄아울렛 SPACE1  37.616258  127.152429

In [49]:
tf['종류']="시장 및 마트"
tf['이미지주소']=pd.NA
tf['설명']=tf['시장명']+"의 설명"
tf

C:\Temp\ipykernel_7276\3735414676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['종류']="시장 및 마트"
C:\Temp\ipykernel_7276\3735414676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['이미지주소']=pd.NA
C:\Temp\ipykernel_7276\3735414676.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf['설명']=tf['시장명']+"의 설명"

,시장명,WGS84위도,WGS84경도,종류,이미지주소,설명
67,진접농협 로컬푸드직매장,37.711246,127.186172,시장 및 마트,<NA>,진접농협 로컬푸드직매장의 설명
70,와부농협 로컬푸드직매장,37.594126,127.224948,시장 및 마트,<NA>,와부농협 로컬푸드직매장의 설명
219,장현 전통시장,37.717616,127.180891,시장 및 마트,<NA>,장현 전통시장의 설명
344,(주)이마트 다산점,37.608204,127.157754,시장 및 마트,<NA>,(주)이마트 다산점의 설명
348,LG마트 덕소점,37.584697,127.214019,시장 및 마트,<NA>,LG마트 덕소점의 설명
425,(주)이마트 남양주점,37.655047,127.243053,시장 및 마트,<NA>,(주)이마트 남양주점의 설명
452,롯데쇼핑(주)롯데마트덕소점,37.584697,127.214019,시장 및 마트,<NA>,롯데쇼핑(주)롯데마트덕소점의 설명
521,홈플러스(주)남양주진접점,37.721747,127.188607,시장 및 마트,<NA>,홈플러스(주)남양주진접점의 설명
718,이마트 별내점,37.642810,127.125968,시장 및 마트,<NA>,이마트 별내점의 설명
820,롯데쇼핑(주)롯데마트 마석점,37.650139,127.309296,시장 및 마트,<NA>,롯데쇼핑(주)롯데마트 마석점의 설명
842,주식회사 이마트 진접점,37.708831,127.182031,시장 및 마트,<NA>,주식회사 이마트 진접점의 설명
996,한성몰 남양주점,37.656536,127.281640,시장 및 마트,<NA>,한성몰 남양주점의 설명
997,코리아마트,37.656536,127.281640,시장 및 마트,<NA>,코리아마트의 설명
1052,현대프리미엄아울렛 SPACE1,37.616258,127.152429,시장 및 마트,<NA>,현대프리미엄아울렛 SPACE1의 설명

In [54]:
df=pd.read_csv('data.csv')
df

,이름,위도,경도,종류,이미지주소,설명
0,용암산,37.732281,127.140046,자연관광지,NaN,용암산의 설명
1,천마산,37.657910,127.300352,자연관광지,https://lh5.googleusercontent.com/p/AF1QipO-oW...,천마산의 설명
2,수락산,37.700247,127.102905,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN3EA...,수락산의 설명
3,문안산,37.635320,127.349141,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPSgy...,문안산의 설명
4,산들소리 수목원,37.651076,127.101550,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNlyk...,산들소리 수목원의 설명
5,물의정원,37.557509,127.313218,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNuH4...,물의정원의 설명
6,비금계곡,37.757117,127.283531,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNkaH...,비금계곡의 설명
7,축령산자연휴양림,37.754777,127.313246,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNfA0...,축령산자연휴양림의 설명
8,물맑음수목원,37.705770,127.295603,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOn-q...,물맑음수목원의 설명
9,남양주오남호수공원,37.693908,127.225337,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMcXc...,남양주오남호수공원의 설명
10,남양주 슬로시티길,37.565830,127.291557,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMdtu...,남양주 슬로시티길의 설명
11,남양주다산길,37.593933,127.185566,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN1OL...,남양주다산길의 설명
12,철마산,37.726300,127.189886,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMPlU...,철마산의 설명
13,운길산,37.571148,127.302641,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOkcx...,운길산의 설명
14,석화촌,37.651057,127.191447,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPjEC...,석화촌의 설명
15,팔당유원지,37.550159,127.252970,자연관광지,https://lh5.googleusercontent.com/p/AF1QipM2r8...,팔당유원지의 설명
16,수동국민관광지,37.747152,127.281320,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPzzs...,수동국민관광지의 설명
17,피아노폭포,37.631557,127.347047,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPAHx...,피아노폭포의 설명
18,몽골문화촌,37.757721,127.274980,명소,https://lh5.googleusercontent.com/p/AF1QipOLQm...,몽골문화촌의 설명
19,실학박물관,37.516017,127.300603,명소,https://lh5.googleusercontent.com/p/AF1QipMXqN...,실학박물관의 설명
20,수종사,37.571148,127.302641,명소,https://lh5.googleusercontent.com/p/AF1QipMCIV...,수종사의 설명
21,축령산자연휴양림,37.754777,127.313246,명소,https://lh5.googleusercontent.com/p/AF1QipNfA0...,축령산자연휴양림의 설명
22,주필거미박물관,37.567128,127.282462,체험관광지,https://lh5.googleusercontent.com/p/AF1QipPr2O...,주필거미박물관의 설명
23,고로쇠마을,37.763980,127.281830,체험관광지,NaN,고로쇠마을의 설명
24,오남공룡체험전시관,37.695242,127.249016,체험관광지,https://lh5.googleusercontent.com/p/AF1QipOavP...,오남공룡체험전시관의 설명
25,남양주시화도푸른물센터,37.631557,127.347047,체험관광지,NaN,남양주시화도푸른물센터의 설명

In [57]:
tf.columns[3:]

Index(['종류', '이미지주소', '설명'], dtype='object')

In [58]:
tf.columns=['이름','위도','경도']+list(tf.columns[3:])
tf

,이름,위도,경도,종류,이미지주소,설명
67,진접농협 로컬푸드직매장,37.711246,127.186172,시장 및 마트,<NA>,진접농협 로컬푸드직매장의 설명
70,와부농협 로컬푸드직매장,37.594126,127.224948,시장 및 마트,<NA>,와부농협 로컬푸드직매장의 설명
219,장현 전통시장,37.717616,127.180891,시장 및 마트,<NA>,장현 전통시장의 설명
344,(주)이마트 다산점,37.608204,127.157754,시장 및 마트,<NA>,(주)이마트 다산점의 설명
348,LG마트 덕소점,37.584697,127.214019,시장 및 마트,<NA>,LG마트 덕소점의 설명
425,(주)이마트 남양주점,37.655047,127.243053,시장 및 마트,<NA>,(주)이마트 남양주점의 설명
452,롯데쇼핑(주)롯데마트덕소점,37.584697,127.214019,시장 및 마트,<NA>,롯데쇼핑(주)롯데마트덕소점의 설명
521,홈플러스(주)남양주진접점,37.721747,127.188607,시장 및 마트,<NA>,홈플러스(주)남양주진접점의 설명
718,이마트 별내점,37.642810,127.125968,시장 및 마트,<NA>,이마트 별내점의 설명
820,롯데쇼핑(주)롯데마트 마석점,37.650139,127.309296,시장 및 마트,<NA>,롯데쇼핑(주)롯데마트 마석점의 설명
842,주식회사 이마트 진접점,37.708831,127.182031,시장 및 마트,<NA>,주식회사 이마트 진접점의 설명
996,한성몰 남양주점,37.656536,127.281640,시장 및 마트,<NA>,한성몰 남양주점의 설명
997,코리아마트,37.656536,127.281640,시장 및 마트,<NA>,코리아마트의 설명
1052,현대프리미엄아울렛 SPACE1,37.616258,127.152429,시장 및 마트,<NA>,현대프리미엄아울렛 SPACE1의 설명

In [60]:
df=pd.concat([df,tf])
df

,이름,위도,경도,종류,이미지주소,설명
0,용암산,37.732281,127.140046,자연관광지,NaN,용암산의 설명
1,천마산,37.657910,127.300352,자연관광지,https://lh5.googleusercontent.com/p/AF1QipO-oW...,천마산의 설명
2,수락산,37.700247,127.102905,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN3EA...,수락산의 설명
3,문안산,37.635320,127.349141,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPSgy...,문안산의 설명
4,산들소리 수목원,37.651076,127.101550,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNlyk...,산들소리 수목원의 설명
5,물의정원,37.557509,127.313218,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNuH4...,물의정원의 설명
6,비금계곡,37.757117,127.283531,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNkaH...,비금계곡의 설명
7,축령산자연휴양림,37.754777,127.313246,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNfA0...,축령산자연휴양림의 설명
8,물맑음수목원,37.705770,127.295603,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOn-q...,물맑음수목원의 설명
9,남양주오남호수공원,37.693908,127.225337,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMcXc...,남양주오남호수공원의 설명
10,남양주 슬로시티길,37.565830,127.291557,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMdtu...,남양주 슬로시티길의 설명
11,남양주다산길,37.593933,127.185566,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN1OL...,남양주다산길의 설명
12,철마산,37.726300,127.189886,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMPlU...,철마산의 설명
13,운길산,37.571148,127.302641,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOkcx...,운길산의 설명
14,석화촌,37.651057,127.191447,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPjEC...,석화촌의 설명
15,팔당유원지,37.550159,127.252970,자연관광지,https://lh5.googleusercontent.com/p/AF1QipM2r8...,팔당유원지의 설명
16,수동국민관광지,37.747152,127.281320,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPzzs...,수동국민관광지의 설명
17,피아노폭포,37.631557,127.347047,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPAHx...,피아노폭포의 설명
18,몽골문화촌,37.757721,127.274980,명소,https://lh5.googleusercontent.com/p/AF1QipOLQm...,몽골문화촌의 설명
19,실학박물관,37.516017,127.300603,명소,https://lh5.googleusercontent.com/p/AF1QipMXqN...,실학박물관의 설명
20,수종사,37.571148,127.302641,명소,https://lh5.googleusercontent.com/p/AF1QipMCIV...,수종사의 설명
21,축령산자연휴양림,37.754777,127.313246,명소,https://lh5.googleusercontent.com/p/AF1QipNfA0...,축령산자연휴양림의 설명
22,주필거미박물관,37.567128,127.282462,체험관광지,https://lh5.googleusercontent.com/p/AF1QipPr2O...,주필거미박물관의 설명
23,고로쇠마을,37.763980,127.281830,체험관광지,NaN,고로쇠마을의 설명
24,오남공룡체험전시관,37.695242,127.249016,체험관광지,https://lh5.googleusercontent.com/p/AF1QipOavP...,오남공룡체험전시관의 설명
25,남양주시화도푸른물센터,37.631557,127.347047,체험관광지,NaN,남양주시화도푸른물센터의 설명
67,진접농협 로컬푸드직매장,37.711246,127.186172,시장 및 마트,NaN,진접농협 로컬푸드직매장의 설명
70,와부농협 로컬푸드직매장,37.594126,127.224948,시장 및 마트,NaN,와부농협 로컬푸드직매장의 설명
219,장현 전통시장,37.717616,127.180891,시장 및 마트,NaN,장현 전통시장의 설명
344,(주)이마트 다산점,37.608204,127.157754,시장 및 마트,NaN,(주)이마트 다산점의 설명
348,LG마트 덕소점,37.584697,127.214019,시장 및 마트,NaN,LG마트 덕소점의 설명
425,(주)이마트 남양주점,37.655047,127.243053,시장 및 마트,NaN,(주)이마트 남양주점의 설명
452,롯데쇼핑(주)롯데마트덕소점,37.584697,127.214019,시장 및 마트,NaN,롯데쇼핑(주)롯데마트덕소점의 설명
521,홈플러스(주)남양주진접점,37.721747,127.188607,시장 및 마트,NaN,홈플러스(주)남양주진접점의 설명
718,이마트 별내점,37.642810,127.125968,시장 및 마트,NaN,이마트 별내점의 설명
820,롯데쇼핑(주)롯데마트 마석점,37.650139,127.309296,시장 및 마트,NaN,롯데쇼핑(주)롯데마트 마석점의 설명
842,주식회사 이마트 진접점,37.708831,127.182031,시장 및 마트,NaN,주식회사 이마트 진접점의 설명
996,한성몰 남양주점,37.656536,127.281640,시장 및 마트,NaN,한성몰 남양주점의 설명
997,코리아마트,37.656536,127.281640,시장 및 마트,NaN,코리아마트의 설명
1052,현대프리미엄아울렛 SPACE1,37.616258,127.152429,시장 및 마트,NaN,현대프리미엄아울렛 SPACE1의 설명

In [61]:
df.to_csv('data.csv',index=False)

In [4]:
df.to_csv('data.csv')

In [11]:
y=37.56
x=127.2
df['거리']=df.apply(lambda d:geopy.distance.distance((y,x),(d['위도'],d['경도'])),axis=1)
df=df[df['거리']<=100]
model = KNeighborsClassifier(n_neighbors=min(5,len(df)))
model.fit(df[['경도', '위도']].values, df[['이름']].values)
near=model.predict([[x,y]])[0]
near

c:\Users\anyou\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

'남양주 슬로시티길'

In [28]:
df

,이름,위도,경도,종류,이미지주소,거리
0,용암산,37.732281,127.140046,자연관광지,NaN,19.839932538690697 km
1,천마산,37.657910,127.300352,자연관광지,https://lh5.googleusercontent.com/p/AF1QipO-oW...,14.021590237838321 km
2,수락산,37.700247,127.102905,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN3EA...,17.76950481591901 km
3,문안산,37.635320,127.349141,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPSgy...,15.599701777598044 km
4,산들소리 수목원,37.651076,127.101550,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNlyk...,13.332395640203492 km
5,물의정원,37.557509,127.313218,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNuH4...,10.007334959952537 km
6,비금계곡,37.757117,127.283531,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNkaH...,23.08618353572713 km
7,축령산자연휴양림,37.754777,127.313246,자연관광지,https://lh5.googleusercontent.com/p/AF1QipNfA0...,23.816084303730648 km
8,물맑음수목원,37.705770,127.295603,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOn-q...,18.247426958871532 km
9,남양주오남호수공원,37.693908,127.225337,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMcXc...,15.029677401313684 km
10,남양주 슬로시티길,37.565830,127.291557,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMdtu...,8.114973209266465 km
11,남양주다산길,37.593933,127.185566,자연관광지,https://lh5.googleusercontent.com/p/AF1QipN1OL...,3.9760874740920586 km
12,철마산,37.726300,127.189886,자연관광지,https://lh5.googleusercontent.com/p/AF1QipMPlU...,18.4792161902234 km
13,운길산,37.571148,127.302641,자연관광지,https://lh5.googleusercontent.com/p/AF1QipOkcx...,9.152174468074659 km
14,석화촌,37.651057,127.191447,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPjEC...,10.134533631006107 km
15,팔당유원지,37.550159,127.252970,자연관광지,https://lh5.googleusercontent.com/p/AF1QipM2r8...,4.806179589951103 km
16,수동국민관광지,37.747152,127.281320,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPzzs...,21.97661895611694 km
17,피아노폭포,37.631557,127.347047,자연관광지,https://lh5.googleusercontent.com/p/AF1QipPAHx...,15.22216694511571 km
18,몽골문화촌,37.757721,127.274980,명소,https://lh5.googleusercontent.com/p/AF1QipOLQm...,22.92065196932691 km
19,실학박물관,37.516017,127.300603,명소,https://lh5.googleusercontent.com/p/AF1QipMXqN...,10.14322200303583 km
20,수종사,37.571148,127.302641,명소,https://lh5.googleusercontent.com/p/AF1QipMCIV...,9.152174468074659 km
21,축령산자연휴양림,37.754777,127.313246,명소,https://lh5.googleusercontent.com/p/AF1QipNfA0...,23.816084303730648 km
22,주필거미박물관,37.567128,127.282462,체험관광지,https://lh5.googleusercontent.com/p/AF1QipPr2O...,7.328372871642592 km
23,고로쇠마을,37.763980,127.281830,체험관광지,NaN,23.763170742374474 km
24,오남공룡체험전시관,37.695242,127.249016,체험관광지,https://lh5.googleusercontent.com/p/AF1QipOavP...,15.621582829383518 km
25,남양주시화도푸른물센터,37.631557,127.347047,체험관광지,NaN,15.22216694511571 km

In [62]:
df['경도'].min()

127.101550237

In [20]:
tmp.km

156.87614940188664

In [18]:
Distance(17.76950481591901)

NameError: name 'Distance' is not defined

In [27]:
for value in df.values:
    print(value)

['용암산' 37.7322805943997 127.140046332149 '자연관광지' nan
 Distance(19.839932538690697)]
['천마산' 37.6579103478731 127.300352454876 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipO-oW8-TGiy8-81vVB9bQOUWpZtwbTcUpoQcsSY=w426-h240-k-no'
 Distance(14.021590237838321)]
['수락산' 37.7002465445 127.1029045433 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipN3EAAicu3t8CaWI6li_GDJIUtryh6Ikm27WBkh=w426-h240-k-no'
 Distance(17.76950481591901)]
['문안산' 37.6353200223398 127.349141031048 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipPSgyx55SYQ2FsoRUHFBTaUvazykPvmM7NErCVe=w408-h306-k-no'
 Distance(15.599701777598044)]
['산들소리 수목원' 37.6510762965 127.101550237 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipNlyksIMKTwfWA1HWA24MmTDRgJOGt7Xl9VEMTC=w408-h306-k-no'
 Distance(13.332395640203492)]
['물의정원' 37.5575094633 127.3132181686 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipNuH4oAl5ySyFyhXwBH22OkjUq-LqdLYInVPO3l=w408-h306-k-no'
 Distance(10.007334959952537)]
['비금계곡' 37.7571165112509 127.283531439174 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipNkaH6J6u4mOXHTqwIIEV0AmPL7jxOR3XWdlial=w408-h306-k-no'
 Distance(23.08618353572713)]
['축령산자연휴양림' 37.7547771162 127.3132455526 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipNfA0MQy0afV8SWEf2MUj91IW2D-Mwk3j2cwqsy=w408-h327-k-no'
 Distance(23.816084303730648)]
['물맑음수목원' 37.70576957 127.2956028276 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipOn-qcUDs5lXFLIOJSP-ubwnLFsU3JFM4jT4ifL=w408-h306-k-no'
 Distance(18.247426958871532)]
['남양주오남호수공원' 37.6939075668 127.225336941 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipMcXcWPjXXEmw-ezbL4QIchfffvZg58NZOCXL_d=w408-h306-k-no'
 Distance(15.029677401313684)]
['남양주 슬로시티길' 37.5658300227253 127.291556594076 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipMdtuJok0We2h55N4gMGx2xOCuGfNTngC5zGQQx=w408-h306-k-no'
 Distance(8.114973209266465)]
['남양주다산길' 37.5939325401 127.1855663465 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipN1OLLKKDp11LZeRtpHG0IYouR6YI2sfvdUMpCB=w426-h240-k-no'
 Distance(3.9760874740920586)]
['철마산' 37.7263004861766 127.189886481276 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipMPlURl4SFyHU9qENhiVgtPEG0m2Zd4-bXE69Kh=w408-h306-k-no'
 Distance(18.4792161902234)]
['운길산' 37.5711477923 127.3026412617 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipOkcxMbfQylQJpQjz88iey4on2qDMuLfsaiTIi5=w408-h306-k-no'
 Distance(9.152174468074659)]
['석화촌' 37.6510572517 127.1914472629 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipPjECbSd1OazDwy6OE5nyzbYBQAScJM2jKOwtoG=w408-h306-k-no'
 Distance(10.134533631006107)]
['팔당유원지' 37.5501588054455 127.252969637051 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipM2r85Ri8ug4nD_uTeHfLJmy-ok48DgwQ7pSg2u=w408-h306-k-no'
 Distance(4.806179589951103)]
['수동국민관광지' 37.7471523394 127.2813198723 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipPzzsokU-EDnT70nyFKsqc3XpZQ_bJlt-2Ah6nJ=w408-h306-k-no'
 Distance(21.97661895611694)]
['피아노폭포' 37.6315567826 127.3470474426 '자연관광지'
 'https://lh5.googleusercontent.com/p/AF1QipPAHxWYcc0VZ_mM9nGBEDL-paGHD_R5jsSdor4O=w426-h240-k-no'
 Distance(15.22216694511571)]
['몽골문화촌' 37.7577206981 127.2749798841 '명소'
 'https://lh5.googleusercontent.com/p/AF1QipOLQmEnyCaQZjSDh7GCJrLVDAaiZcNxgKT8BoeJ=w408-h306-k-no'
 Distance(22.92065196932691)]
['실학박물관' 37.5160172754 127.300602572 '명소'
 'https://lh5.googleusercontent.com/p/AF1QipMXqNjRcrDnVGBKmqu2Iun3NrQcbvCyJuKjUXk=w408-h306-k-no'
 Distance(10.14322200303583)]
['수종사' 37.5711477923 127.3026412617 '명소'
 'https://lh5.googleusercontent.com/p/AF1QipMCIVE2MTvrjfi72_7pPciBHsq-tvYiVXjrCtMb=w408-h306-k-no'
 Distance(9.152174468074659)]
['축령산자연휴양림' 37.7547771162 127.3132455526 '명소'
 'https://lh5.googleusercontent.com/p/AF1QipNfA0MQy0afV8SWEf2MUj91IW2D-Mwk3j2cwqsy=w408-h327-k-no'
 Distance(23.816084303730648)]
['주필거미박물관' 37.5671283461 127.2824618647 '체험관광지'
 'https://lh5.googleusercontent.com/p/AF1QipPr2OaMkaRAbAYnykmlT_rLHrv1VQGun-ZJWLkG=w408-h306-k-no'
 Distance(7.328372871642592)]
['고로쇠마을' 37.7639797602 127.2818298239 '체험관광지' nan
 Distance(23.763170742374474)]
['오남공룡체험전시관' 37.6952417689343 127.24901557001 '체험관광지'
 'https://lh5.googleusercontent.com/p/AF1QipOavPWjJ8hDwPTaS0aFQvc0YMV5iRK3EdGnI3J9=w408-h361-k-no'
 Distance(15.621582829383518)]
['남양주시화도푸른물센터' 37.6315567826 127.3470474426 '체험관광지' nan
 Distance(15.22216694511571)]